% make plots comparing NI predictions to measured PP thresholds for third
% and fourth order ternary texture planes

%% Load the data

pp = loadTernaryPP(fullfile('data', 'mtc_soid_xlsrun_summ.mat'), ...
    'subjects', '*');

%% Load the NI predictions

ni = open(fullfile('save', 'TernaryNIPredictions_PennNoSky_2x32_square.mat'));

%%

uniqueSubjects = unique(pp.subjects);
uniqueColors = lines(length(uniqueSubjects));
colorMap = containers.Map(uniqueSubjects, num2cell(uniqueColors, 2));

% color for NI
colorMap('subject') = [0 0.3438 0.7410];

plotTernaryMatrix({ni.predictions, pp}, 'ellipse', false, ...
    'groupMaskFct', @(g) length(g) > 6 && sum(g == ';') == 0, ...
    'beautifyOptions', {'ticks', 'off', 'ticklabels', false, ...
        'titlesize', 12, 'titleweight', 'normal', 'noaxes', true, ...
        'fontscale', 0.667}, ...
    'triangleOptions', {'fontscale', 0.667, 'edgelabels', 'digit'}, ...
    'limits', 1.5, ...
    'titleShift', [0 -0.5], 'titleAlignment', {'center', 'bottom'}, ...
    'labelOptions', {'FontSize', 8, 'subscriptSpacing', -0.55, ...
        'coeffToStr', @(i) plusMinus(i)}, ...
    'colorFct', colorMap);

%% Make plot

plusMinus = '+-';
plotTernaryMatrix({ni.predictions, pp}, 'ellipse', false, ...
    'groupMaskFct', @(g) length(g) > 6 && sum(g == ';') == 0, ...
    'beautifyOptions', {'ticks', 'off', 'ticklabels', false, ...
        'titlesize', 12, 'titleweight', 'normal', 'noaxes', true, ...
        'fontscale', 0.667}, ...
    'triangleOptions', {'fontscale', 0.667, 'edgelabels', 'digit'}, ...
    'limits', 1.5, ...
    'plotterOptions', {'fixedShape', [1 4], 'fixedSize', [6 1.5], ...
    'fixedSizeUnits', 'inches'}, ...
    'titleShift', [0 -0.5], 'titleAlignment', {'center', 'bottom'}, ...
    'labelOptions', {'FontSize', 8, 'subscriptSpacing', -0.55, ...
        'coeffToStr', @(i) plusMinus(i)});
preparegraph;

% safePrint(fullfile('figs', 'draft', 'ternaryHigherOrderNIPPMatch.pdf'));
